// Generated by CoffeeScript 1.6.3
(function() {
  var GoogleStrategy, Issue, IssueSchema, MongoURL, User, UserSchema, app, childProcess, client, express, fs, http, io, localURL, moment, mongoose, passport, path, prodURL, realmset, returnURLset, routes, server, socketio, sys, util, _ref;

  express = require('express');

  routes = require('./../routes');

  http = require('http');

  path = require('path');

  fs = require('fs');

  util = require('util');

  socketio = require('socket.io');

  mongoose = require('mongoose');

  moment = require('moment');

  passport = require('passport');

  GoogleStrategy = require('passport-google').Strategy;

  client = require('twilio')('ACe1b7313b5b376f66c4db568dfa97e3e9', '1a3442ad88426e0561ed5d4fd4ae71e1');

  sys = require('sys');

  childProcess = require('child_process');

  app = express();

  app.set('port', process.env.PORT || 3000);

  app.set('views', __dirname + './../views');

  app.set('view engine', 'jade');

  app.use(express.favicon());

  app.use(express.logger('dev'));

  app.use(express.cookieParser());

  app.use(express.bodyParser());

  app.use(express.methodOverride());

  app.use(express.session({
    secret: 'keyboard cat'
  }));

  app.use(passport.initialize());

  app.use(passport.session());

  app.use(app.router);

  app.use(express["static"](path.join(__dirname, './../public')));

  if ('development' === app.get('env')) {
    app.use(express.errorHandler());
  }

  server = http.createServer(app);

  io = socketio.listen(server);

  MongoURL = (_ref = process.env.MONGOHQ_URL) != null ? _ref : 'mongodb://localhost';

  mongoose.connect(MongoURL);

  moment().format();

  IssueSchema = new mongoose.Schema({
    issue: String,
    username: String,
    displayName: String,
    lesson: String,
    date: Object,
    timeStamp: Object,
    time: Object,
    totalWait: Object,
    isComplete: Boolean,
    comment: String
  });

  Issue = mongoose.model('Issue', IssueSchema);

  UserSchema = new mongoose.Schema({
    _id: {
      type: String,
      required: true
    },
    openId: String,
    displayName: String,
    emails: String
  });

  User = mongoose.model('User', UserSchema);

  prodURL = 'http://intense-dawn-1429.herokuapp.com';

  localURL = 'http://localhost:3000';

  returnURLset = process.env.PROD ? prodURL : localURL;

  realmset = process.env.PROD ? prodURL : localURL;

  passport.use(new GoogleStrategy({
    returnURL: returnURLset + '/auth/google/return',
    realm: realmset
  }, function(identifier, profile, done) {
    console.log('email', profile.emails[0]['value']);
    return User.find({
      _id: profile.emails[0]['value']
    }, function(err, user) {
      done(err, user[0]);
      console.log('uu', user[0]);
      if (user.length === 0) {
        User.create({
          openId: identifier,
          _id: profile.emails[0]['value'],
          displayName: profile.displayName,
          emails: profile.emails[0]['value']
        }, function(err, user) {
          done(err, user[0]);
        });
        return;
      }
    });
  }));

  passport.serializeUser(function(user, done) {
    return done(null, user);
  });

  passport.deserializeUser(function(obj, done) {
    return done(null, obj);
  });

  app.get('/auth/google', passport.authenticate('google'));

  app.get('/auth/google/return', passport.authenticate('google', {
    session: true,
    successRedirect: '/student',
    failureRedirect: '/'
  }));

  io.sockets.on('connection', function(socket) {
    console.log('hello from your socket server');
    socket.on('issueObj', function(issueObj) {
      var current_time, date, issue, timeStamp;
      date = moment().format('L');
      timeStamp = moment().format('X');
      current_time = moment().format('lll');
      issue = new Issue({
        issue: issueObj.newIssue,
        username: issueObj.username,
        displayName: issueObj.displayName,
        date: date,
        timeStamp: timeStamp,
        time: current_time,
        isComplete: false,
        comment: 'None'
      });
      issue.save();
      /*
      		#Send an SMS text message via Twilio
      		client.sendMessage {
      			to:'+16145519436',
      			from: '+13036256825',
      			body: issueObj.displayName+' '+issueObj.newIssue+'.'
      			}, (err, responseData) -> 
      			if !err
      				console.log responseData.from
      				console.log responseData.body
      */

      return io.sockets.emit('issue', issue);
    });
    socket.on('issueEditObj', function(issueEditObj) {
      Issue.findByIdAndUpdate(issueEditObj.issueId, {
        issue: issueEditObj.issue
      }, function(err, issue) {
        if (err) {
          return console.log('ERROR!');
        } else {
          return console.log('Edited and Updated!');
        }
      });
      return io.sockets.emit('issueEditObj', issueEditObj);
    });
    socket.on('completeObj', function(completeObj) {
      Issue.findByIdAndUpdate(completeObj.issueId, {
        totalWait: completeObj.totalWait,
        isComplete: completeObj.isComplete,
        comment: completeObj.comment
      }, function(err, issue) {
        if (err) {
          return console.log('ERROR!');
        } else if (completeObj.comment === 'Figured out on own') {
          return console.log('figuredoutonown');
          /*
          					#If figured out on own
          					#Send an SMS text message via Twilio
          					client.sendMessage {
          						to:'+16145519436',
          						from: '+13036256825',
          						body: Issue.displayName+' '+completeObj.comment+'.'
          						}, (err, responseData) -> 
          						if !err
          							console.log responseData.from
          							console.log responseData.body
          */

        } else {
          return console.log('Completed and Updated!');
        }
      });
      return io.sockets.emit('completeObj', completeObj);
    });
    return socket.on('lessonUpdate', function(lessonUpdate) {
      return Issue.update({
        date: lessonUpdate.date
      }, {
        lesson: lessonUpdate.lesson
      }, function(err, numberAffected, raw) {
        if (err) {
          console.log('ERROR');
        } else {

        }
        console.log('The number of updated docs was ', numberAffected);
        return console.log('The raw response from Mongo was ', raw);
      });
    });
  });

  app.get('/', function(req, res) {
    return res.render('login', {
      user: req.user
    });
  });

  /*
  Student Routing
  */


  app.get('/student', function(req, res) {
    return res.render('student', {
      user: req.user
    });
  });

  app.get('/currentrequests', function(req, res) {
    return res.render('currentrequests', {
      user: req.user
    });
  });

  app.get('/currReq', function(req, res) {
    var currUser;
    currUser = req.user._id;
    return Issue.find({
      username: currUser,
      isComplete: false
    }, function(err, issue) {
      if (err) {
        return console.log('ERROR');
      } else {
        return res.send(issue);
      }
    });
  });

  app.get('/pastrequests', function(req, res) {
    return res.render('pastrequests', {
      user: req.user
    });
  });

  app.get('/pastReq', function(req, res) {
    var currUser;
    currUser = req.user._id;
    return Issue.find({
      username: currUser,
      isComplete: true
    }, function(err, issue) {
      if (err) {
        return console.log('ERROR');
      } else {
        return res.send(issue);
      }
    });
  });

  app.get('/logout', function(req, res) {
    req.logout();
    return res.redirect('/');
  });

  /*
  Teacher Routing
  */


  app.get('/teacher', function(req, res) {
    return res.render('teacher');
  });

  app.get('/found', function(req, res) {
    return Issue.find({
      isComplete: false
    }, function(err, issue) {
      if (err) {
        return console.log('ERROR');
      } else {
        return res.send(issue);
      }
    });
  });

  app.get('/reports', function(req, res) {
    return res.render('reports', {
      user: req.user
    });
  });

  app.get('/reportsInfo', function(req, res) {
    return Issue.find({}, function(err, issue) {
      if (err) {
        return console.log('ERROR');
      } else {
        return res.send(issue);
      }
    });
  });

  server.listen(app.get('port'), function() {
    return console.log('Express server listening on port ' + app.get('port'));
  });

}).call(this);
